name: automated build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setting the dependencies up
      run: sudo apt install libfontconfig1-dev zlib1g-dev libjsoncpp-dev libgtksourceviewmm-3.0-dev libgtkmm-3.0-dev cmake ninja-build
    - name: installing cLaTeXMath
      run: ./install-clatexmath.sh
    - name: configure
      run: cmake -G "Ninja" -DHAVE_CLATEXMATH=ON .
    - name: ninja
      run: ninja
    - name: compress header files
      run: 7z a -r linux-latest.zip .
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: linux-latest.zip
        
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: build-artifact-ubuntu-latest
        path: .
